first-workflow

diff --git a/.github/workflows/first-workflow.yaml b/.github/workflows/first-workflow.yaml
--- a/.github/workflows/first-workflow.yaml
+++ b/.github/workflows/first-workflow.yaml
@@ -13,7 +13,8 @@ jobs:
       run: ls
 
     - name: read file
-      run: cat README.md
+       run: cat README.md || echo "README.md not found"
+
 
           
          
