General-ASCII

diff --git a/.github/workflows/generate-ascii.yaml b/.github/workflows/generate-ascii.yaml
--- a/.github/workflows/generate-ascii.yaml
+++ b/.github/workflows/generate-ascii.yaml
@@ -9,26 +9,27 @@ jobs:
     - name: Install cowsay program
       run: sudo apt-get install cowsay -y
 
-     - name: Execute cowsay CMD
-       run: cowsay -f dragon "run for cover, I am Dragon...RAWR" >> dragon.txt
+    - name: Execute cowsay CMD
+      run: cowsay -f dragon "run for cover, I am Dragon...RAWR" >> dragon.txt
 
-     - name: sleep for 30 seconds
-       run: sleep 30  
+    - name: Sleep for 30 seconds
+      run: sleep 30  
 
   test_job2: 
-   runs-on: ubuntu-latest
-   steps:
+    runs-on: ubuntu-latest
+    steps:
     - name: Text file exists
-      run: grep -i "dragon" dragon.txt   
+      run: test -f dragon.txt && grep -i "dragon" dragon.txt || echo "File not found"
 
-    - name: sleep for 10 seconds
-      run: 10 seconds
+    - name: Sleep for 10 seconds
+      run: sleep 10
 
   built_job3:
-   runs-on: ubuntu-latest
-   steps: 
+    runs-on: ubuntu-latest
+    steps: 
     - name: Read files
-      run: cat dragon.txt
+      run: cat dragon.txt || echo "File not found"
 
-    - name: deploy
-      run: echo "deploying...."        
+    - name: Deploy
+      run: echo "Deploying...."  
+      
